[workspace]
resolver = "2"
members = [
  "bishin-parser"
]
default-members = [
  "bishin-parser"
]

[workspace.dependencies]
indoc = "2.0"
thiserror = "1"
# winnow = { version = "0.7", features = ["debug"] }
winnow = { version = "0.7" }
