[package]
name = "bishin-collect"
version = "0.1.0"
edition = "2024"

[dependencies]
log.workspace = true
petgraph.workspace = true
thiserror.workspace = true
walkdir.workspace = true

[dev-dependencies]
expect-test.workspace = true
tempfile.workspace = true
