version = 1

[install]
bacon.pkg-path = "bacon"

[vars]
BIN_NAME = "bishin"

[hook]
on-activate = '''
  export PATH="$PWD/target/debug:$PATH"
'''

[include]
environments = [
  {remote = "zmitchell/rust" }
]

[profile]
fish = '''
  abbr install-bin "cargo b -r && cp target/release/$BIN_NAME ~/bin/$BIN_NAME"
  abbr update-tests "UPDATE_EXPECT=1 cargo nextest run --workspace"
  abbr run-tests "cargo nextest run --workspace"
'''
