[package]
name = "bishin-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
indoc.workspace = true
thiserror.workspace = true
winnow.workspace = true

[dev-dependencies]
tempfile.workspace = true
